- type: startingGear
  id: MobsterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSuitBlackMob
    back: ClothingBackpackMafiaFilled
    head: ClothingHeadHatFedoraBlack
    shoes: ClothingShoesBootsLaceup
    neck: ClothingNeckTieBlack
    id: PassengerPDA
    belt: ClothingBeltHolster
  innerclothingskirt: ClothingUniformJumpsuitSuitBlackMob
  satchel: ClothingBackpackMafiaFilled
  duffelbag: ClothingBackpackMafiaFilled

- type: startingGear
  id: MobsterGearAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitSuitBrown
    back: ClothingBackpackMafiaFilled
    head: ClothingHeadHatFlatBrown
    shoes: ClothingShoesLeather
    neck: ClothingNeckTieBrown
    id: PassengerPDA
    belt: ClothingBeltSuspendersBlack
    pocket1: CombatKnife
  innerclothingskirt: ClothingUniformJumpsuitSuitBrown
  satchel: ClothingBackpackMafiaFilled
  duffelbag: ClothingBackpackMafiaFilled

#Oldstation Roles

- type: startingGear
  id: OldstationMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    neck: ClothingNeckStethoscope
    shoes: ClothingShoesColorWhite
    id: MedicalIDCard
    pocket1: Brutepack
    pocket2: GlowstickBase
    belt: ClothingBeltMedical
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  
  
- type: startingGear
  id: OldstationGuard
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    shoes: ClothingShoesBootsJack
    id: SecurityIDCard
    pocket1: Flash
    pocket2: GlowstickBase
  innerclothingskirt: ClothingUniformJumpskirtSec
  
- type: startingGear
  id: OldstationEngi
  equipment:
    jumpsuit: ClothingUniformJumpsuitEngineering
    shoes: ClothingShoesBootsWork
    id: EngineeringIDCard
    mask: ClothingMaskBreath
    gloves: ClothingHandsGlovesColorYellowBudget
    pocket1: EmergencyOxygenTankFilled
    pocket2: GlowstickBase
    belt: ClothingBeltUtility
  innerclothingskirt: ClothingUniformJumpskirtEngineering
  
- type: startingGear
  id: OldstationScientist
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    shoes: ClothingShoesColorWhite
    id: ResearchIDCard
    pocket1: Pen
    pocket2: GlowstickBase
  innerclothingskirt: ClothingUniformJumpsuitAncient